server:
  port: 8080

spring:
  application:
    name: Quartz-Sample

  ## DataBase
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    generate-ddl: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    scheduler-name: "sample"

# Logging Info
logging:
  level:
    org.springframework: info